### ISSUE TITLE
完善 Rime Vim Mode：支持 Linux & 自动切换回中文模式

### ISSUE THREAD

**Issue by lei4519** [lei4519/blog#85]
1

**Comment by IC-killer** [comment]
@lei4519 看起来挺不错，linux下怎么配置app_options，
使用linux/ubuntu的话要怎么获取应用包名称？我的squirrel.custom.yaml下配置似乎无效：
```yaml
app_options:
  nvim:
    ascii_mode: true
    vmode: true
```
> vim_mode.lua脚本中的 if vmode 改为 if true 似乎可以全局工作...

**Comment by IC-killer** [comment]
@lei4519 问题已解决，ubuntu的包名就是apt或命令行用的包名，我把上面的配置放到对应输入方案下的配置文件中就可以生效了，ubuntu下squirrel.custom.yaml好像不能用？

**Comment by lei4519** [comment]
> @lei4519 问题已解决，ubuntu的包名就是apt或命令行用的包名，我把上面的配置放到对应输入方案下的配置文件中就可以生效了，ubuntu下squirrel.custom.yaml好像不能用？

linux 的配置文件要写在 fcitx5.custom.yaml 中（如果用的是 fcitx5）

不过 linux 中我遇到一个问题还没解决，就是 `vim_mode.lua` 这个 `lua_processor` 是配置在中文拼音里的，所以 `esc` 从中文切换到 `ascii` 是正常的，但在 `ascii mode` 中按 `i/a/c/o` 并不会重新进入中文模式

**Comment by IC-killer** [comment]
@lei4519 你描述这个现象我也遇到了，iaco不会回到中文模式，比较尴尬的是我的配置不知道哪里出错又失效了，之前判断不一定准确，回复先删掉了，重新尝试中。。。额

**Comment by IC-killer** [comment]
把脚本里面的 if vmode 改到if 1会全局生效, 
我的配置，app_options没有生效，测试用的date_translator生效：
```yaml
patch:
  engine/translators/+:
    - lua_translator@*date_translator  # 日期时间变量输出
  translator/preedit_format: []
  engine/processors/+:
    - lua_processor@*vim_mode

  switches/+:
    - name: vmode
      reset: 0

  app_options/nvim:
    - ascii_mode: true
      vmode: true
```
